mutation forgotPassword($credentials: EmailInput!) {
  forgotPassword(credentials: $credentials) {
    success
    message
  }
}

mutation resetPassword($credentials: NewPasswordInput!) {
  resetPassword(credentials: $credentials) {
    success
    message
    token
  }
}
