input UserInput {
  email: String!
  name: String
  username: String!
  password: String
}

type User {
  id: Int
  email: String
  name: String
  username: String
}

type Query {
  user: User
  users: [User]
}

type Mutation {
  createUser(user: UserInput!): User
}
